baseURL = 'https://cegepmv.github.io/420-312'
languageCode = 'fr-fr'
title = 'Réseaux Informatiques'
enableEmoji = true

[module]
  [[module.imports]]
    path = 'hugo-theme-relearn'

[params]
    linkTitle = 'Réseaux Informatiques'
    collapsibleMenu = true
    disableLandingPageButton = true
    themeVariant = ['auto', 'zen-light', 'zen-dark']
    disableInlineCopyToClipBoard = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'